test:
  database: <%= ENV['RDS_DB_NAME'] %>
  adapter: postgresql
  encoding: UTF8
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: <%= ENV['RDS_PORT'] %>
